name: Build S905X armbian GF MESON64 V22

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_git_user:
        description: "armbian / a520ass"
        required: true
        default: "armbian"
      set_git_branch:
        description: "v22.05 / v22.05.3 / v22.08"
        required: true
        default: "v22.08"
      set_branch:
        description: "Branch: edge / current / legacy"
        required: false
        default: "current"
      set_release:
        description: "Release: jammy / focal / bullseye"
        required: false
        default: "jammy"
      set_desktop:
        description: "Build Desktop: no / gnome / xfce, etc."
        required: false
        default: "no"
  #schedule:
    #- cron: "0 17 * * 0"

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install -y $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir
          echo "COMPILE_STARTINGTIME=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_ENV

          ARR_BRANCH=("edge" "current" "legacy")
          set_branch="${{ github.event.inputs.set_branch }}"
          if  [[ -z "${set_branch}" || -z "$(echo "${ARR_BRANCH[@]}" | grep -w "${set_branch}")" ]]; then
              set_branch="current"
          fi
          echo "ARMBIAN_BRANCH=${set_branch}" >> $GITHUB_ENV

          ARR_RELEASE=("jammy" "focal" "bullseye")
          set_release="${{ github.event.inputs.set_release }}"
          if  [[ -z "${set_release}" || -z "$(echo "${ARR_RELEASE[@]}" | grep -w "${set_release}")" ]]; then
              set_release="focal"
          fi
          echo "ARMBIAN_RELEASE=${set_release}" >> $GITHUB_ENV

          # Desktop Environment Options: https://github.com/armbian/build/tree/master/config/desktop/bullseye/environments
          ARR_DESKTOP=("no" "budgie" "cinnamon" "gnome" "mate" "xmonad" "xfce")
          set_desktop="${{ github.event.inputs.set_desktop }}"
          if  [[ "${set_desktop}" != "no" && -n "$(echo "${ARR_DESKTOP[@]}" | grep -w "${set_desktop}")" ]]; then
              # Desktop configuration: https://github.com/armbian/build/tree/master/config/desktop
              str_desktop="BUILD_DESKTOP=yes DESKTOP_ENVIRONMENT=${set_desktop} DESKTOP_ENVIRONMENT_CONFIG_NAME=config_basic"
              edition_name="${set_desktop}_desktop"
          else
              str_desktop="BUILD_DESKTOP=no"
              edition_name="server"
          fi
          echo "ARMBIAN_DESKTOP_STR=${str_desktop}" >> $GITHUB_ENV
          echo "ARMBIAN_DESKTOP_OPT=${edition_name}" >> $GITHUB_ENV

      - name: Download source code
        id: down
        run: |
          git clone --depth 1 -b ${{ github.event.inputs.set_git_branch }} https://github.com/${{ github.event.inputs.set_git_user }}/build.git

      - name: Compile Armbian [ Board is MESON64 S905X / Edition is ${{ env.ARMBIAN_DESKTOP_OPT }} ]
        id: compile
        run: |
          # Compile method and parameter description: https://docs.armbian.com/Developer-Guide_Build-Options
          cd build/
          git clone https://github.com/a520ass/armbian-n1-userpatch userpatches
          sudo chmod +x compile.sh
          sudo ./compile.sh \
          BRANCH=${{ env.ARMBIAN_BRANCH }} \
          RELEASE=${{ env.ARMBIAN_RELEASE }} \
          BUILD_MINIMAL=no \
          ${{ env.ARMBIAN_DESKTOP_STR }} \
          KERNEL_ONLY=no \
          KERNEL_CONFIGURE=no \
          COMPRESS_OUTPUTIMAGE=sha,gz
          echo "::set-output name=status::success"

      - name: Upload Armbian image to Release
        uses: ncipollo/release-action@main
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          tag: Armbian_Aml_S905X_GF_MESON64_V22_${{ env.COMPILE_STARTINGTIME }}
          artifacts: build/output/images/*,build/output/debs/*
          allowUpdates: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            This is Armbian image for S905X
            * Firmware information
            Default username: root
            Default password: 1234
